import type { Metadata } from "next";
import localFont from "next/font/local";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';
import Providers from '@/store/Providers';
import { ThemeProvider } from "@/components/theme/DarkMode";
import { SessionWrapper } from "@/components/SessionWrapper";
import { SocketProvider } from "@/context/SocketContext";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'react-image-crop/dist/ReactCrop.css'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    // 

        <html lang={locale}>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-nightBlack`}
            >
              <ToastContainer/>
              <NextIntlClientProvider messages={messages}>
                <Providers>
                  <ThemeProvider>
                  <SessionWrapper>
                    <SocketProvider>
                    {children}
                    </SocketProvider>
                  </SessionWrapper>
                  </ThemeProvider>
                </Providers>
              </NextIntlClientProvider>
            </body>
          
        </html>
   
    // 
  );
}
