name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - subbranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Verify Secrets
      run: echo "Checking secrets..." && [ -n "${{ secrets.MONGO_URI_ATLAS }}" ] && echo "Secret is set" || echo "Secret is missing"

    - name: Login to docker hub
      run: echo "${{ secrets.DOCKER_KEY }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t vineeth1927/closer-client \
          --build-arg NODE_ENV='development' \
          --build-arg NEXT_PUBLIC_BACKEND_URL='${{ secrets.BACKEND_URL }}' \
          --build-arg NEXTAUTH_URL='${{ secrets.CLIENT_BASE_URL }}' .

    - name: Publish Image to docker hub
      run: docker push vineeth1927/closer-client:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull image from docker hub
      run: docker pull vineeth1927/closer-client:latest

    - name: Delete old container (if exists)
      run: docker rm -f nextjs-app-container || true

    - name: Run Docker Container
      run: docker run -d -p 3000:80 --name nextjs-app-container \
          -e MONGO_URI_ATLAS='${{ secrets.MONGO_URI_ATLAS }}' \
          vineeth1927/closer-client
