name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - subbranch
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env.local
        echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.local
        echo "GITHUB_ID=${{ secrets.GITHUB_ID }}" >> .env.local
        echo "GITHUB_SECRET=${{ secrets.GITHUB_SECRET }}" >> .env.local
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.local
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.local
        echo "NEXT_PUBLIC_PAYMENT_KEY_ID=${{ secrets.NEXT_PUBLIC_PAYMENT_KEY_ID }}" >> .env.local
        echo "NEXT_PUBLIC_PAYMENT_KEY_SECRET=${{ secrets.NEXT_PUBLIC_PAYMENT_KEY_SECRET }}" >> .env.local
        echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env.local
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.local
        echo "MONGO_URI_ATLAS=${{ secrets.MONGO_URI_ATLAS }}" >> .env.local
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.local

    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_KEY }}
    
    - name: Build Docker Image
      run: docker build -t vineeth1927/closer-client:latest --build-arg NODE_ENV='development' --build-arg NEXT_PUBLIC_BACKEND_URL='${{ secrets.BACKEND_URL}}' --build-arg NEXTAUTH_URL='${{ secrets.CLIENT_BASE_URL}}' --build-arg MONGO_URI_ATLAS='${{ secrets.MONGO_URI_ATLAS }}' .
    
    - name: Publish Image to docker hub
      run: docker push vineeth1927/closer-client:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
     - name: Pull image from docker hub
       run: docker pull vineeth1927/closer-client:latest

     - name: Delete old container
       run: docker rm -f nextjs-app-container

     - name: Create .env.local file on the server
       run: |
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env.local
        echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.local
        echo "GITHUB_ID=${{ secrets.GITHUB_ID }}" >> .env.local
        echo "GITHUB_SECRET=${{ secrets.GITHUB_SECRET }}" >> .env.local
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.local
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.local
        echo "NEXT_PUBLIC_PAYMENT_KEY_ID=${{ secrets.NEXT_PUBLIC_PAYMENT_KEY_ID }}" >> .env.local
        echo "NEXT_PUBLIC_PAYMENT_KEY_SECRET=${{ secrets.NEXT_PUBLIC_PAYMENT_KEY_SECRET }}" >> .env.local
        echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env.local
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.local
        echo "MONGO_URI_ATLAS=${{ secrets.MONGO_URI_ATLAS }}" >> .env.local
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.local

     - name: Run Docker Container
       run: docker run -d -p 3000:3000 --name nextjs-app-container vineeth1927/closer-client:latest

